import type { z } from 'zod';

interface EnvField {
  key: string;
  type: string;
  required: boolean;
  default?: unknown;
  description?: string;
}

/**
 * Convert camelCase to SCREAMING_SNAKE_CASE
 * poolSize -> POOL_SIZE
 * NODE_ENV -> NODE_ENV (already uppercase, unchanged)
 */
function toScreamingSnake(str: string): string {
  // If already all uppercase/underscores, return as-is
  if (/^[A-Z0-9_]+$/.test(str)) {
    return str;
  }
  // Convert camelCase to SCREAMING_SNAKE_CASE
  return str
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .toUpperCase();
}

/**
 * Convert path to environment variable name
 * server.port -> SERVER__PORT
 * database.poolSize -> DATABASE__POOL_SIZE
 * NODE_ENV -> NODE_ENV
 */
function pathToEnvKey(path: string, prefix: string = ''): string {
  const envKey = path
    .split('.')
    .map(toScreamingSnake)
    .join('__');

  return prefix ? `${prefix}${envKey}` : envKey;
}

/**
 * Extract fields from a Zod schema for env example generation
 */
function extractEnvFields(
  schema: z.ZodType,
  prefix: string = '',
  envPrefix: string = ''
): EnvField[] {
  const fields: EnvField[] = [];

  if ('shape' in schema && typeof schema.shape === 'object') {
    const shape = schema.shape as Record<string, z.ZodType>;

    for (const [key, value] of Object.entries(shape)) {
      const path = prefix ? `${prefix}.${key}` : key;

      // Recursively handle nested objects
      if ('shape' in value) {
        fields.push(...extractEnvFields(value, path, envPrefix));
      } else {
        fields.push(getEnvFieldInfo(value, path, envPrefix));
      }
    }
  }

  return fields;
}

/**
 * Get field information for env example
 */
function getEnvFieldInfo(zodType: z.ZodType, path: string, envPrefix: string): EnvField {
  let type = 'string';
  let required = true;
  let defaultValue: unknown;
  let description: string | undefined;

  let current = zodType;

  if ('_def' in current) {
    const def = current._def as Record<string, unknown>;

    if (def.typeName === 'ZodOptional') {
      required = false;
      current = def.innerType as z.ZodType;
    }

    if (def.typeName === 'ZodDefault') {
      required = false;
      defaultValue = typeof def.defaultValue === 'function'
        ? (def.defaultValue as () => unknown)()
        : def.defaultValue;
      current = def.innerType as z.ZodType;
    }

    if (def.description && typeof def.description === 'string') {
      description = def.description;
    }

    // Get type from unwrapped type
    const innerDef = ('_def' in current ? current._def : {}) as Record<string, unknown>;
    const typeName = innerDef.typeName as string;

    switch (typeName) {
      case 'ZodString':
        type = 'string';
        break;
      case 'ZodNumber':
        type = 'number';
        break;
      case 'ZodBoolean':
        type = 'boolean';
        break;
      case 'ZodEnum':
        type = `enum: ${(innerDef.values as string[]).join(' | ')}`;
        break;
      default:
        type = typeName?.replace('Zod', '').toLowerCase() ?? 'unknown';
    }
  }

  const field: EnvField = {
    key: pathToEnvKey(path, envPrefix),
    type,
    required,
  };

  if (defaultValue !== undefined) field.default = defaultValue;
  if (description !== undefined) field.description = description;

  return field;
}

/**
 * Generate .env.example file content from a Zod schema
 */
export function generateEnvExample(
  schema: z.ZodType,
  options: { prefix?: string; includeComments?: boolean } = {}
): string {
  const { prefix = '', includeComments = true } = options;
  const fields = extractEnvFields(schema, '', prefix);
  const lines: string[] = [];

  if (includeComments) {
    lines.push('# Configuration Environment Variables');
    lines.push('# Generated by zonfig');
    lines.push('');
  }

  for (const field of fields) {
    if (includeComments) {
      // Add comment with description and type info
      const comments: string[] = [];

      if (field.description) {
        comments.push(`# ${field.description}`);
      }

      comments.push(`# Type: ${field.type}${field.required ? ' (required)' : ' (optional)'}`);

      lines.push(...comments);
    }

    // Add the env var line
    let value = '';
    if (field.default !== undefined) {
      value = String(field.default);
    } else if (field.type === 'string') {
      value = '';
    } else if (field.type === 'number') {
      value = '0';
    } else if (field.type === 'boolean') {
      value = 'false';
    }

    lines.push(`${field.key}=${value}`);
    lines.push('');
  }

  return lines.join('\n').trim() + '\n';
}
